#!/bin/bash
set -ex

pkgver=$1

pushd chromium-$pkgver/out/Release/cronet

# Define bazel module
cat > MODULE.bazel <<EOF
module(name = "cronet_native", version = "${pkgver}")

bazel_dep(name = "rules_cc", version = "0.2.14")
EOF

cat > BUILD.bazel <<EOF
load("@rules_cc//cc:cc_import.bzl", "cc_import")

cc_import(
  name = "cronet_native",
  hdrs = [
    "include/cronet_c.h",
    "include/cronet_export.h",
    "include/cronet.idl_c.h",
    "include/bidirectional_stream_c.h",
  ],
  shared_library = "libcronet.${pkgver}.so",
  strip_include_prefix = "include",
  visibility = ["//visibility:public"],
)
EOF

popd

tar -czf cronet_native-$pkgver-linux-x86_64.tar.gz -C chromium-$pkgver/out/Release/cronet .

cat > bazel/cronet_native.MODULE.bazel <<EOF
# AUTOGENERATED FILE, DO NOT EDIT

bazel_dep(name = "cronet_native", version = "${pkgver}")
archive_override(
    module_name = "cronet_native",
    url = "https://github.com/zifeitong/libcronet/releases/download/${pkgver}/cronet_native-${pkgver}-linux-x86_64.tar.gz",
    sha256 = "`sha256sum cronet_native-${pkgver}-linux-x86_64.tar.gz | awk '{print $1}'`",
)
EOF
