#!/bin/bash
set -ex

pkgver=$1

pushd chromium-$pkgver/out/Release/cronet

# Define bazel module
cat > MODULE.bazel <<EOF
module(name = "cronet_native", version = "${pkgver}")
EOF

cat > BUILD.bazel <<EOF
cc_import(
  name = "cronet_native",
  hdrs = [
    "cronet_c.h",
    "cronet_export.h",
    "cronet.idl_c.h",
    "bidirectional_stream_c.h",
  ],
  shared_library = "libcronet.${pkgver}.so",
)
EOF

popd

tar -czf cronet_native-$pkgver-linux-x86_64.tar.gz -C chromium-$pkgver/out/Release/cronet .

cat > bazel/cronet_native.MODULE.bazel <<EOF
# AUTOGENERATED FILE, DO NOT EDIT

bazel_dep(name = "cronet_native", version = "${pkgver}")
archive_override(
    module_name = "cronet_native",
    url = "https://github.com/zifeitong/libcronet/releases/download/${pkgver}/cronet_native-${pkgver}-linux-x86_64.tar.gz",
    sha256 = "`sha256sum cronet_native-${pkgver}-linux-x86_64.tar.gz | awk '{print $1}'`",
)
EOF
