#!/bin/bash
set -ex

pkgver=$1

pushd chromium-$pkgver/out/release/cronet

# Define bazel module
cat > MODULE.bazel <<EOF
module(name = "prebuilt_cronet_native", version = "${pkgver}")

bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "platforms", version = "1.0.0")
EOF

cat > BUILD.bazel <<EOF
load("@rules_cc//cc:cc_import.bzl", "cc_import")

config_setting(
    name = "cpu_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64"
    ],
)

config_setting(
    name = "cpu_arm64",
    constraint_values = [
        "@platforms//cpu:arm64"
    ],
)

cc_import(
  name = "prebuilt_cronet_native",
  hdrs = [
    "include/cronet_c.h",
    "include/cronet_export.h",
    "include/cronet.idl_c.h",
    "include/bidirectional_stream_c.h",
  ],
  shared_library = select({
    ":cpu_x86_64": "x86_64/libcronet.${pkgver}.so",
    ":cpu_arm64": "arm64/libcronet.${pkgver}.so",
  }),
  strip_include_prefix = "include",
  visibility = ["//visibility:public"],
)
EOF

mkdir x86_64 arm64
mv libcronet.${pkgver}.so x86_64/

popd

# Copy arm64 shared library
mv chromium-$pkgver/out/release_arm64/cronet/libcronet.${pkgver}.so chromium-$pkgver/out/release/cronet/arm64/

tar -czf prebuilt_cronet_native-$pkgver-linux.tar.gz -C chromium-$pkgver/out/release/cronet .

cat > bazel/prebuilt_cronet_native.MODULE.bazel <<EOF
# AUTOGENERATED FILE, DO NOT EDIT

bazel_dep(name = "prebuilt_cronet_native", version = "${pkgver}")
archive_override(
    module_name = "prebuilt_cronet_native",
    url = "https://github.com/zifeitong/libcronet/releases/download/${pkgver}/prebuilt_cronet_native-${pkgver}-linux.tar.gz",
    sha256 = "`sha256sum prebuilt_cronet_native-${pkgver}-linux.tar.gz | awk '{print $1}'`",
)
EOF
