name: Build and release cronet-native

on: workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set environment variables
        run: echo "VERSION=`cat VERSION`" >> $GITHUB_ENV

      - name: Build cronet
        run: scripts/build.sh $VERSION

      - name: Package
        run: scripts/package.sh $VERSION

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 0.0
          files: cronet-native-${{ env.VERSION }}.tar.gz
